### PR TITLE
Add FuguIta: Live OpenBSD system

### PR DESCRIPTION
**Pull request by e-zk**
_FuguIta_ is a Live System based on OpenBSD that is designed to be run
from removable media: http://fuguita.org/.

A large portion of developer documentation is in Japanese so I've made
a note of that as well.

### CODE REVIEW

**Comment by ligurio** [comment]
@e-zk could you explain why web site address contains "i" (http://fuguita.org/) and distro name everywhere contains "l" instead ("L" in lower case)?

**Comment by e-zk** [comment]
The name doesn't contain a lowercase L anywhere on the webpage.   
Most sans-serif fonts make the uppercase "i" look like a lowercase "l": "FuguIta" == `FuguIta`.

Copy/paste the name from any text on the webpage into a terminal with a monospaced font, it is all "FuguIta". :)

**Comment by leonstafford** [comment]
Fun facts from site:

> Note: FuguIta (河豚板) stands for "Blowfish Disk" in Japanese. Fugu means blowfish, and Ita means something flat such as a plate, a disk or a board etc...
Some Japanese might associate those who cook when hearing Ita. For them, so FuguIta also means "Blowfish Cook" as double meaning

2n character in "fugu" (豚), means pig. First, "kawa" (河), so transliteration of _fugu_ is "river pig". Which is funny, but [seems it comes from Chinese](https://justhungry.com/fugu-are-you-pig), where blowfish were found in large rivers. TIL

**Comment by quobit** [comment]
thanks @e-zk

**Pull request merged**
